package commands

import (
	"encoding/json"
	"fmt"
	"strings"
)

// Per-host renderers turn the read/write/destructive classification into safety config.
// Each emits both binary (Bash) patterns and MCP tool patterns where the host supports them,
// so an agent driving tgctl either way hits the same rails.

// renderClaudeCode emits a Claude Code settings.json fragment: destructive ops in deny,
// writes in ask, reads in allow — for both Bash and MCP tool invocations.
func renderClaudeCode(c classification) (string, error) {
	deny := make([]string, 0)
	ask := make([]string, 0)
	allow := make([]string, 0)
	for _, cmd := range c.Destructive {
		deny = append(deny, bashPattern(cmd.Path), mcpToolPattern(cmd.Path))
	}
	for _, cmd := range c.Write {
		ask = append(ask, bashPattern(cmd.Path), mcpToolPattern(cmd.Path))
	}
	for _, cmd := range c.Read {
		allow = append(allow, bashPattern(cmd.Path), mcpToolPattern(cmd.Path))
	}
	settings := map[string]any{
		"permissions": map[string]any{
			"deny":  deny,
			"ask":   ask,
			"allow": allow,
		},
		"_comment": "Generated by `tgctl agent guard --host claude-code`. Merge into ~/.claude/settings.json. " +
			"deny = irreversible (delete/leave/ban); ask = writes; allow = reads. MCP-only operation is the hard guarantee.",
	}
	b, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return "", err
	}
	return string(b) + "\n", nil
}

// renderCodex emits a Codex config.toml: a read-only sandbox with approvals required, plus a
// commented list of the irreversible commands a reviewer should never auto-approve.
func renderCodex(c classification) (string, error) {
	var b strings.Builder
	b.WriteString("# Generated by `tgctl agent guard --host codex`.\n")
	b.WriteString("# Read-only sandbox: tgctl writes require explicit approval; reads run freely.\n")
	b.WriteString("approval_policy = \"on-request\"\n\n")
	b.WriteString("[sandbox]\n")
	b.WriteString("mode = \"read-only\"\n\n")
	b.WriteString("# Never auto-approve these irreversible tgctl operations:\n")
	for _, cmd := range c.Destructive {
		fmt.Fprintf(&b, "#   tgctl %s   (%s)\n", cmd.Path, cmd.Method)
	}
	b.WriteString("\n# These writes should require approval:\n")
	for _, cmd := range c.Write {
		fmt.Fprintf(&b, "#   tgctl %s   (%s)\n", cmd.Path, cmd.Method)
	}
	return b.String(), nil
}

// renderOpenCode emits an opencode.json permission map: deny destructive, ask writes, allow
// reads — keyed by the Bash command patterns OpenCode matches.
func renderOpenCode(c classification) (string, error) {
	perms := map[string]string{}
	for _, cmd := range c.Destructive {
		perms[bashPattern(cmd.Path)] = "deny"
	}
	for _, cmd := range c.Write {
		perms[bashPattern(cmd.Path)] = "ask"
	}
	for _, cmd := range c.Read {
		perms[bashPattern(cmd.Path)] = "allow"
	}
	root := map[string]any{
		"$schema":    "https://opencode.ai/config.json",
		"permission": perms,
		"_comment":   "Generated by `tgctl agent guard --host opencode`. Merge into opencode.json.",
	}
	b, err := json.MarshalIndent(root, "", "  ")
	if err != nil {
		return "", err
	}
	return string(b) + "\n", nil
}
