package commands

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

// Per-host renderers turn the read/write/destructive classification into safety config.
// Each emits both binary (Bash) patterns and MCP tool patterns where the host supports them,
// so an agent driving tgctl either way hits the same rails.

// destructiveAPIMethods returns the unique, sorted Bot API method names in the hard-block
// bucket, for the raw `tgctl api <method>` deny rules.
func destructiveAPIMethods(c classification) []string {
	seen := map[string]bool{}
	var out []string
	for _, cmd := range c.Destructive {
		if !seen[cmd.Method] {
			seen[cmd.Method] = true
			out = append(out, cmd.Method)
		}
	}
	sort.Strings(out)
	return out
}

// renderClaudeCode emits the Claude Code guard: a PreToolUse hook script (the enforcement
// layer — it de-obfuscates quote/backslash tricks, catches path-invoked binaries like
// ./bin/tgctl, and gates the raw `tgctl api <method>` escape hatch) plus a settings.json
// fragment with deny/ask/allow permission rules and the hook wiring. The permission rules
// are belt-and-suspenders: Claude matches them as literal command prefixes, so only the
// hook defeats obfuscation and path-prefixed invocations.
func renderClaudeCode(c classification) (string, error) {
	deny := make([]string, 0)
	ask := make([]string, 0)
	allow := make([]string, 0)
	for _, cmd := range c.Destructive {
		// Every alias path too — "tgctl msg delete" and "tgctl message delete-many"
		// invoke the same deleteMessage(s) as "tgctl message delete".
		for _, p := range cmd.AllPaths() {
			deny = append(deny, bashPattern(p))
		}
		deny = append(deny, mcpToolPattern(cmd.Path))
	}
	// Raw `tgctl api <method>` escape hatch: deny the known-destructive Bot API methods
	// by name. These are exact prefix rules; the hook goes further and blocks every
	// non-get method, because Telegram treats method names case-insensitively
	// (DELETEMESSAGE works) which literal prefix rules cannot cover.
	for _, m := range destructiveAPIMethods(c) {
		deny = append(deny, bashPattern("api "+m))
	}
	// `tgctl alias set` can mint a shorthand that expands to a blocked command before
	// cobra parses it (tgctl alias set x "message delete"; tgctl x) — deny creating
	// new indirections.
	deny = append(deny, bashPattern("alias set"))
	for _, cmd := range c.Write {
		for _, p := range cmd.AllPaths() {
			ask = append(ask, bashPattern(p))
		}
		ask = append(ask, mcpToolPattern(cmd.Path))
	}
	for _, cmd := range c.Read {
		for _, p := range cmd.AllPaths() {
			allow = append(allow, bashPattern(p))
		}
		allow = append(allow, mcpToolPattern(cmd.Path))
	}

	// ${CLAUDE_PROJECT_DIR} is the Claude runtime variable; Claude substitutes it when
	// loading the hook — it is NOT expanded here.
	hookPath := "${CLAUDE_PROJECT_DIR}/.claude/hooks/tgctl-guard.sh"
	hookEntry := func(matcher string) map[string]any {
		return map[string]any{
			"matcher": matcher,
			"hooks":   []any{map[string]any{"type": "command", "command": hookPath}},
		}
	}
	settings := map[string]any{
		"permissions": map[string]any{
			"deny":  deny,
			"ask":   ask,
			"allow": allow,
		},
		"hooks": map[string]any{
			// Hook both Bash and the tgctl MCP namespace.
			"PreToolUse": []any{hookEntry("Bash"), hookEntry("mcp__tgctl__")},
		},
		"_comment": "Generated by `tgctl agent guard --host claude-code`. Save the hook script above to " +
			".claude/hooks/tgctl-guard.sh (chmod +x) and merge this fragment into .claude/settings.json. " +
			"deny = irreversible (delete/leave/ban/revoke/refund/unpin-all) incl. alias paths and raw-api methods; " +
			"ask = writes; allow = reads. MCP-only operation is the hard guarantee.",
	}
	b, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return "", err
	}

	var out strings.Builder
	out.WriteString("# ----- .claude/hooks/tgctl-guard.sh (save + chmod +x) -----\n")
	out.WriteString(hookScript(c))
	out.WriteString("\n# ----- merge into .claude/settings.json -----\n")
	out.Write(b)
	out.WriteString("\n")
	return out.String(), nil
}

// hookScript generates the PreToolUse hook. Commands are matched by exact SUBCOMMAND PATH
// at the command position — never by bare verbs anywhere in the line — with an optional
// path prefix before the binary so ./bin/tgctl and /usr/local/bin/tgctl are caught too.
// The raw `tgctl api <method>` escape hatch is gated at the method position: only
// read-only get* methods pass, because Bot API method names are case-insensitive
// server-side (DELETEMESSAGE works), so an allowlist of destructive names is not enough.
func hookScript(c classification) string {
	seenCLI := map[string]bool{}
	seenTool := map[string]bool{}
	var cliPaths, toolNames []string
	for _, cmd := range c.Destructive {
		for _, p := range cmd.AllPaths() {
			if !seenCLI[p] {
				seenCLI[p] = true
				cliPaths = append(cliPaths, p)
			}
		}
		if t := mcpToolPattern(cmd.Path); !seenTool[t] {
			seenTool[t] = true
			toolNames = append(toolNames, t)
		}
	}
	// `alias set` can rewrite a future invocation into a blocked command before cobra
	// parses it — block minting new indirections on the Bash surface.
	if !seenCLI["alias set"] {
		cliPaths = append(cliPaths, "alias set")
	}
	sort.Strings(cliPaths)
	sort.Strings(toolNames)

	var cliArray strings.Builder
	cliArray.WriteString("blocked_cmds=(\n")
	for _, p := range cliPaths {
		// Escape any single quotes in the path (there should be none, but be safe).
		safe := strings.ReplaceAll(p, "'", "'\\''")
		cliArray.WriteString("  '" + safe + "'\n")
	}
	cliArray.WriteString(")")

	var toolArray strings.Builder
	toolArray.WriteString("blocked_tools=(\n")
	for _, t := range toolNames {
		safe := strings.ReplaceAll(t, "'", "'\\''")
		toolArray.WriteString("  '" + safe + "'\n")
	}
	toolArray.WriteString(")")

	return `#!/usr/bin/env bash
# tgctl agent guard — blocks irreversible tgctl operations on the Bash and MCP
# surfaces. Generated by ` + "`tgctl agent guard`" + `; regenerate after upgrading
# tgctl so new commands (and their aliases) are covered.
#
# MATCHING STRATEGY: commands are matched by exact SUBCOMMAND PATH at the
# command position, not by bare verbs anywhere in the line. This prevents:
#   - false positives: 'tgctl message send --text "how to delete a message"'
#     is NOT blocked because "message send" is not in the blocked set.
#   - false negatives: alias paths (msg delete, message delete-many, cmds
#     delete) are enumerated in blocked_cmds alongside the canonical paths.
#
# For each blocked cli-path P, we check whether the CLEANED command string
# matches the anchored ERE:
#   (^|[;&|([:space:]]+)([^[:space:]]*/)?tgctl[[:space:]]+<P>([[:space:];&|)]|$)
# which ensures tgctl+P appears at a command position. The optional
# ([^[:space:]]*/)? prefix also catches path-invoked binaries like
# ./bin/tgctl or /usr/local/bin/tgctl, while a different binary that merely
# ends in "tgctl" (mytgctl) is NOT matched. The trailing class also covers
# "tgctl webhook delete;true" where a separator directly follows the verb.
#
# The MCP branch is an exact set-membership check — no glob or regex.
#
# The raw "tgctl api <method>" escape hatch is gated at the METHOD position:
# only read-only get* methods pass. Bot API method names are case-insensitive
# server-side (DELETEMESSAGE works), so everything not starting with "get" —
# including flags-before-method invocations — is blocked. A -q value or path
# that merely CONTAINS "delete" is not affected.
#
# De-obfuscation: quotes (\042 / \047) and backslash (\134) are stripped from
# the raw command string before pattern matching to defeat trivial tricks like
#   tgctl message de""lete --id 5
# Variable indirection (a=delete; tgctl message $a) and shell aliases are NOT
# defeated — use MCP-only mode or a read-only sandbox for a hard guarantee.

# --- blocked command paths (Bash surface; canonical + cobra alias paths) ---
` + cliArray.String() + `

# --- blocked MCP tool names (exact) ---
` + toolArray.String() + `

input=$(cat)

# deny_raw emits a denial with a FIXED reason via printf (no jq needed).
deny_raw() {
  printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"%s"}}\n' "$1"
  exit 0
}

# deobfuscate strips quote chars (\042=", \047=', \134=\) and collapses
# newlines to a single line so obfuscation tricks can't split a token across
# lines. Applied in BOTH the jq and no-jq branches.
deobfuscate() {
  printf '%s' "$1" | tr -d '\042\047\134' | tr '\n' ' '
}

# bash_is_blocked returns 0 (true) if the cleaned command contains a blocked
# tgctl subcommand path at the command position.
bash_is_blocked() {
  local cleaned="$1"
  local p
  for p in "${blocked_cmds[@]}"; do
    # Paths are "word word" so only spaces need escaping to [[:space:]]+.
    local pat
    pat=$(printf '%s' "$p" | sed 's/ /[[:space:]]+/g')
    if printf '%s' "$cleaned" | grep -qiE "(^|[;&|([:space:]]+)([^[:space:]]*/)?tgctl[[:space:]]+${pat}([[:space:];&|)]|\$)"; then
      return 0
    fi
  done
  return 1
}

# api_is_blocked returns 0 (true) if the command invokes the raw "tgctl api"
# escape hatch with anything other than a read-only get* method. Separators
# are flattened first so every api invocation in a compound line is scanned
# ("tgctl api getMe;tgctl api deleteWebhook" cannot hide behind the first
# match), then the token after each "api" is checked case-insensitively.
api_is_blocked() {
  local cleaned="$1"
  local flat m
  flat=$(printf '%s' "$cleaned" | tr ';|&()' '     ')
  while IFS= read -r m; do
    [ -n "$m" ] || continue
    case "$m" in
      [Gg][Ee][Tt]*) ;; # read-only getX methods are allowed
      *) return 0 ;;
    esac
  done < <(printf '%s' "$flat" \
    | grep -oE "(^|[[:space:]])([^[:space:]]*/)?tgctl[[:space:]]+api[[:space:]]+[^[:space:]]+" \
    | sed -E 's/^.*[[:space:]]api[[:space:]]+//')
  return 1
}

# Without jq we cannot isolate the tool_name/command fields. Fail safe: apply
# the same de-obfuscation and anchored path matching on the raw payload rather
# than a loose tgctl.*verb scan that would flag any Bash line mentioning
# tgctl+verb (e.g. "cat message_delete.go").
if ! command -v jq >/dev/null 2>&1; then
  # Flatten JSON structure chars as well: after quote-stripping the payload
  # reads {command:tgctl message delete ...}, which would leave tgctl glued to
  # "command:" and never match the anchored patterns.
  flat=$(printf '%s' "$input" | tr '\n{}:,' '     ')
  cleaned=$(deobfuscate "$flat")
  if bash_is_blocked "$cleaned"; then
    deny_raw "tgctl agent guard: irreversible operation blocked (jq unavailable; raw match)."
  fi
  if api_is_blocked "$cleaned"; then
    deny_raw "tgctl agent guard: raw api call blocked (jq unavailable; raw match)."
  fi
  exit 0
fi

# deny emits the denial with a jq-escaped reason so an interpolated value
# can never break out of the JSON string.
deny() {
  jq -c -n --arg r "$1" \
    '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:$r}}'
  exit 0
}

tool=$(printf '%s' "$input" | jq -r '.tool_name // empty')
case "$tool" in
  Bash)
    raw_cmd=$(printf '%s' "$input" | jq -r '.tool_input.command // empty')
    cleaned=$(deobfuscate "$raw_cmd")
    if bash_is_blocked "$cleaned"; then
      deny "tgctl agent guard: irreversible operation blocked."
    fi
    if api_is_blocked "$cleaned"; then
      deny "tgctl agent guard: raw api call blocked (only get* methods pass). Use dedicated commands or MCP-only mode."
    fi
    ;;
  *)
    # MCP branch: exact set-membership — no substring or regex match.
    for t in "${blocked_tools[@]}"; do
      if [ "$tool" = "$t" ]; then
        deny "tgctl agent guard: irreversible MCP tool blocked (${tool})."
      fi
    done
    ;;
esac
exit 0
`
}

// renderCodex emits a Codex config.toml: a read-only sandbox with approvals required, plus a
// commented list of the irreversible commands a reviewer should never auto-approve.
func renderCodex(c classification) (string, error) {
	var b strings.Builder
	b.WriteString("# Generated by `tgctl agent guard --host codex`.\n")
	b.WriteString("# Read-only sandbox: tgctl writes require explicit approval; reads run freely.\n")
	b.WriteString("approval_policy = \"on-request\"\n\n")
	b.WriteString("[sandbox]\n")
	b.WriteString("mode = \"read-only\"\n\n")
	b.WriteString("# Never auto-approve these irreversible tgctl operations (nor their cobra\n")
	b.WriteString("# alias paths, e.g. `tgctl msg delete`, `tgctl message delete-many`):\n")
	for _, cmd := range c.Destructive {
		fmt.Fprintf(&b, "#   tgctl %s   (%s)\n", cmd.Path, cmd.Method)
	}
	b.WriteString("#\n")
	b.WriteString("# The raw escape hatch `tgctl api <method>` can call ANY Bot API method and\n")
	b.WriteString("# method names are case-insensitive server-side — never auto-approve an api\n")
	b.WriteString("# call whose method does not start with `get`.\n")
	b.WriteString("# `tgctl alias set` can mint a shorthand for a blocked command — never\n")
	b.WriteString("# auto-approve it.\n")
	b.WriteString("\n# These writes should require approval:\n")
	for _, cmd := range c.Write {
		fmt.Fprintf(&b, "#   tgctl %s   (%s)\n", cmd.Path, cmd.Method)
	}
	return b.String(), nil
}

// renderOpenCode emits an opencode.json permission map: deny destructive (canonical and
// alias paths, plus destructive raw-api methods and `alias set`), ask writes, allow reads —
// keyed by the Bash command patterns OpenCode matches.
func renderOpenCode(c classification) (string, error) {
	perms := map[string]string{}
	for _, cmd := range c.Destructive {
		for _, p := range cmd.AllPaths() {
			perms[bashPattern(p)] = "deny"
		}
	}
	for _, m := range destructiveAPIMethods(c) {
		perms[bashPattern("api "+m)] = "deny"
	}
	perms[bashPattern("alias set")] = "deny"
	for _, cmd := range c.Write {
		for _, p := range cmd.AllPaths() {
			perms[bashPattern(p)] = "ask"
		}
	}
	for _, cmd := range c.Read {
		for _, p := range cmd.AllPaths() {
			perms[bashPattern(p)] = "allow"
		}
	}
	root := map[string]any{
		"$schema":    "https://opencode.ai/config.json",
		"permission": perms,
		"_comment": "Generated by `tgctl agent guard --host opencode`. Merge into opencode.json. " +
			"deny covers alias paths, destructive raw-api methods, and `alias set`; these are literal " +
			"prefix rules — for obfuscation-resistant blocking use --host claude-code (hook) or MCP-only mode.",
	}
	b, err := json.MarshalIndent(root, "", "  ")
	if err != nil {
		return "", err
	}
	return string(b) + "\n", nil
}
